name: Flask App CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupérer le code source
    - name: Checkout code
      uses: actions/checkout@v4

    # Étape 2 : Configurer Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Étape 3 : Installer les dépendances
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    # Étape 4 : Vérifier que l'application peut démarrer
    - name: Check application startup
      run: |
        source venv/bin/activate
        python -c "from app import app; print('Application startup check successful')"

    # Étape 5 : Déployer sur GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./templates
        enable_jekyll: false
